import DynamicalSystemsInvolvingTransformationsGroupLean.Basic
import DynamicalSystemsInvolvingTransformationsGroupLean.SourcePackage
import DynamicalSystemsInvolvingTransformationsGroupLean.SourceDependencies
import DynamicalSystemsInvolvingTransformationsGroupLean.Formalization
import DynamicalSystemsInvolvingTransformationsGroupLean.ReviewerBridge
import DynamicalSystemsInvolvingTransformationsGroupLean.TheoremStatement
import DynamicalSystemsInvolvingTransformationsGroupLean.MathlibObjects
import DynamicalSystemsInvolvingTransformationsGroupLean.AdmissibleClass
import DynamicalSystemsInvolvingTransformationsGroupLean.Projection
import DynamicalSystemsInvolvingTransformationsGroupLean.BridgeLemmas
import DynamicalSystemsInvolvingTransformationsGroupLean.GateLemmas
import DynamicalSystemsInvolvingTransformationsGroupLean.FinalTheorem
import DynamicalSystemsInvolvingTransformationsGroupLean.TransformationGroupActions
import DynamicalSystemsInvolvingTransformationsGroupLean.InvariantMeasures
import DynamicalSystemsInvolvingTransformationsGroupLean.ErgodicTheorems
import DynamicalSystemsInvolvingTransformationsGroupLean.EntropyTopological
import DynamicalSystemsInvolvingTransformationsGroupLean.MixingProperties
import DynamicalSystemsInvolvingTransformationsGroupLean.SpectralTheory
import DynamicalSystemsInvolvingTransformationsGroupLean.RigidityClassification
import DynamicalSystemsInvolvingTransformationsGroupLean.DynamicsAnalyticFoundation
import DynamicalSystemsInvolvingTransformationsGroupLean.DynamicsRoute

namespace HautevilleHouse
namespace DynamicalSystemsInvolvingTransformationsGroupLean

-- Root module: imports all domain components

def sourceRepository : String :=
  "dynamical-systems-involving-transformations-group-canonical-lane-lean"

def sourceDescription : String :=
  "Dynamical systems involving transformations group: ergodic theory, mixing, entropy, spectral decomposition, and classification"

end DynamicalSystemsInvolvingTransformationsGroupLean
end HautevilleHouse